Team3/feature/i 6 testcases
GatorGauge/GatorGauge pull request #74
Opened 2017-12-08 21:52 UTC by lylet-AC

Can someone fix the flake8 errors please?  My pc has a different version of flake8 and I'm not sure how to downgrade it.  I ran mine and it's still failing travis.

2017-12-10 21:26 UTC, burrowss requested changes
Flake 8 needs to be addressed since it is failing the test case for it

2017-12-11 05:55 UTC, lylet-AC commented
@burrowss would you be able to run the linter, I ran it on my PC and this was the result as stated in the pull req above

2017-12-11 18:39 UTC, karolvargas approved these changes

2017-12-11 18:41 UTC, burrowss approved these changes

2017-12-11 19:19 UTC, mariakimheinert commented
@lylet-AC there are now merge conflicts that must be resolved

2017-12-12 01:48 UTC, merged