Team3/feature/i 4 nlp
GatorGauge/GatorGauge pull request #84
Opened 2017-12-11 22:45 UTC by karolvargas

Code which prints emoji count of ten emojis the user will be allowed to enter at submission time and returns total emoji count

2017-12-11 23:21 UTC, burrowss requested changes
Why did you make a whole extra gensim file when Nick and I have been working on it? Ours works for all of the different features including commits.

2017-12-12 00:05 UTC, yeeunmariakim commented
@karolvargas we're going to remove the gensim and preserve the emoji check

2017-12-12 01:01 UTC, burrowss approved these changes

2017-12-12 01:01 UTC, merged

2017-12-12 15:09 UTC, karolvargas commented
@burrowss I just forgot to delete that file that was my bad. I forgot I had that in the same branch as the emoji counter